// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using FormBizz.EntityFrameworkCore;

#nullable disable

namespace FormBizz.Migrations
{
    [DbContext(typeof(FormBizzDbContext))]
    partial class FormBizzDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            //  Code here!
        }
    }
}
